services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=user_db'
      - 'POSTGRES_PASSWORD=root_password'
      - 'POSTGRES_USER=user_ecommerce'
    ports:
      - '5435:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: