spring:
  application:
    name: BackEnd

  datasource:
    url: jdbc:postgresql://localhost:3306/seu_banco
    username: seu_usuario
    password: sua_senha
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
jwt:
  token:
    private:
      key: classpath:keys/app.key
    public:
      key: classpath:keys/app.pub
server:
  port: 8080